/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "CoffeeHandler"): TruffleContracts.CoffeeHandlerContract;
      require(name: "Context"): TruffleContracts.ContextContract;
      require(name: "ERC20"): TruffleContracts.ERC20Contract;
      require(name: "ERC20Detailed"): TruffleContracts.ERC20DetailedContract;
      require(name: "IERC20"): TruffleContracts.IERC20Contract;
      require(name: "Migrations"): TruffleContracts.MigrationsContract;
      require(name: "Ownable"): TruffleContracts.OwnableContract;
      require(
        name: "WrappedCoffeeCoin"
      ): TruffleContracts.WrappedCoffeeCoinContract;
    }
  }
}
